### ISSUE TITLE
Visualize your Robot's actual state and sensor Data in Unity3D

### ISSUE THREAD

**Issue by Bertrand64300** [siemens/ros-sharp#104]
Hi, I am a beginner in programming and I am working in the way to link RVIZ/GAZEBO with Unity.
I found in your ROS# wiki a link to a Youtube video about “Visualize your Robot's actual state and sensor Data in Unity3D.” and that is exactly what I want to do with a UR5 robot arm.
Problem, I cannot find the joint State Patcher/Kinematic Patcher and Gravity Patcher in your package.
Is it because these data are not public? Can you please help me to understand how I can make it possible? 
Cordially,
Bertrand

**Comment by suzannahsmith1** [comment]
Hi @Bertrand64300,
That video is meant as a showcase only. It uses an old version of ROS#, and some custom scripts that are not included in the base ROS# package. 
It is absolutely possible to model a robot's actual state in Unity, and so far we have a [tutorial](https://github.com/siemens/ros-sharp/wiki/User_App_ROS_GazeboSimulationExample) showing how to do this, using the Turtlebot as an example. Please follow this instead of the showcase video. 
I will now close this issue, since there several other issues open which are closely related to this topic.
Suzannah
