### ISSUE TITLE
how to control urdf axis with c# script

### ISSUE THREAD

**Issue by mhelmrei** [siemens/ros-sharp#142]
Hello,
thanks a lot for sharing this library.

I'm running Unity Version 2018.3.0b9 with the latest ros-sharp from GitHub on Windows 10.

I'm trying to address the joint values of a URDF import in Unity with a custom script. (see script below)
but once the joyAxisWriter is created it disappears in the update() function. (returns null)

Are there some examples and or could you explain how to control the joints of an URDF model with
a c# script?

Best, Matthias

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Linq;
using RosSharp.RosBridgeClient;

public class compas_urdf_handler : MonoBehaviour
{
    float p = 1;
    JointStateWriter joyAxisWriter;

    // Start is called before the first frame update
    private void Start()
    {
        var gameObjects = FindObjectsOfType<GameObject>().Where(g => g.name == "gantry");
        var gantry = gameObjects.First();
        Debug.Log("11Found gantry: " + gantry == null ? "Nope" : "Yay");

        joyAxisWriter = gantry.GetComponent<JointStateWriter>();
        Debug.Log("Found axis writer: " + joyAxisWriter == null ? "Nope" : "Yay");
        
        joyAxisWriter.Write(100);

    }

    // Update is called once per frame
    private void Update()
    {
        Debug.Log(joyAxisWriter == null ? "joyAxisWriter is gone" : "joyAxisWriter is here");
    }
}`

**Comment by MartinBischoff** [comment]
Hi @mhelmrei ,

in your script I see no reason why your `JointStateWriter` object that you named `joyAxisWriter` should become null at some  `Update()`. If it becomes null in your scene, it might be due to other scripts interfering from the outside.

Please take a look at the [code map](https://github.com/siemens/ros-sharp/wiki/Dev_MessageHandlingCodeMap.pdf) to see how the different ROS# scripts interact.
* Both [JointStateSubscriber](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/RosCommuncation/JointStateSubscriber.cs), and [JoyAxisJointTransformWriter](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/MessageHandling/JoyAxisJointTransformWriter.cs) set the joint state via [JointStateWriter](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/MessageHandling/JointStateWriter.cs).
The first one is typically used when reading the joint angle from some ROS system, the second is used when setting the angle from within Unity.
* When using [JoyAxisInputPasser](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/MessageHandling/JoyAxisInputPasser.cs) you can read the user input  from any [Axis](https://docs.unity3d.com/ScriptReference/Input.GetAxis.html) and pass this to [JoyAxisJointTransformWriter](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/MessageHandling/JoyAxisJointTransformWriter.cs) (to animate a joint).
* Alternatively, you can use [JoyAxisInputPasser](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/MessageHandling/JoyAxisInputPasser.cs) to set the target velocity of a hinge joint via [JoyAxisJointMotorWriter](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/MessageHandling/JoyAxisJointMotorWriter.cs) (to simulate the joint).

**Comment by mhelmrei** [comment]
Hi MartinBischoff,
thank you for the swift respond. The issue was solved rather simple. Importing the URDF Model (import) created an object with the same name under "Visuals", so the C# script wasnt finding the right game object.

![image](https://user-images.githubusercontent.com/34544179/49165754-3224ff80-f332-11e8-9434-30a74ab4f32e.png)

Best, Matthias
