### ISSUE TITLE
Change the publication frequency of the topic : camera / depth_registered / ?

### ISSUE THREAD

**Issue by YannRodriguez** [siemens/ros-sharp#230]
Hello ! First of all, I wanted to **thank you** for sharing ROS# as an opensource and to respond in the forum!

I am currently a young beginner in ROS and Unity and I have been working for a few weeks on a project where there is need to model on unity in VR a surface present in front of a camera.

### What I already did:

In the project, a computer (ubuntu) is connected to an intel **realsense2 camera**. Another computer (windows) is connected via a network cable to the previous computer and has a subscriber of **topic / camera / depth_registered /** points on Unity. I use these points in real time to create a mesh thanks to the triangulation method. That leaves me with a rectangle that looks like this:

![image](https://user-images.githubusercontent.com/52059549/61269979-86390300-a7a0-11e9-817f-5f24ddfebe84.png)

### The problems related to my method:

1) The main concern of my method is that the system takes a lot of time to update (~ 50s ,my program is not optimized either I guess). As part of the project I do not need to have a lot of Fps (1 uptdate of the pointclouds per 3 seconds could be enough since the object is not supposed to move). So in front of this flow of information that unity does not seem to manage I could see that it would surely be necessary to compress the pointClouds, but I wanted to know first of all if it was possible to lower the frequency of publication of the topic?

2) I don't care about the colors so I ignore them in the data from sensor_msgs/PointCloud2 Message, can you confirm that this is the optimal topic?

3) Question Unity: Once the mesh is created I need to automate the creation of a collider. Since I did not find a simple way to create it, I wanted to create a terrain, is it a good idea?

Thank you and Have a good Day ! :)

**Comment by berkayalpcakal** [comment]
Hello @YannRodriguez 

In order to generate a custom mesh out of point clouds without using color information, please keep in mind that you do not have to subscribe to "camera / depth_registered / points", which I assume is a pointcloud2 type of messages. You can just subscribe to 2D depth images so that communication and processing take less time. Please see the similar discussion here #211. 

It is possible to lower the frequency of publication on the ROS side, to do that please search it [here](https://answers.ros.org/questions/). Yet, it is possible to lower the frequency of subscription on Unity side. If your subscriber script implements the base class Subscriber.cs, you can see that there is a variable called TimeStep which controls the rate of subscription. 

For Unity related questions please refer to [here](https://answers.unity.com/questions/index.html).

I hope it helps.
