### ISSUE TITLE
split ROS# into individual repositories

### ISSUE THREAD

**Issue by frotein** [siemens/ros-sharp#267]
There is no file_server.launch file in the ROS file_server package.

**Comment by MartinBischoff** [comment]
Hi @frotein ,

why do you need a separate `file_server.launch` file? 

`file_server` is launched together with `rosbridge_websocket` in [ros_sharp_communication](https://github.com/siemens/ros-sharp/blob/master/ROS/file_server/launch/ros_sharp_communication.launch).

In the unusal case that you need the `file_server` service without `rosbridge` you can go with `rosrun file_server file_server`.

**Comment by gonzalocasas** [comment]
Well, is not such an uncommon case to want to use your file server on its own. We use it without ros-sharp, so we detached and forked it: https://github.com/gramaziokohler/ros_file_server

**Comment by MartinBischoff** [comment]
Just asking out of curiosity: What are you using the file_server for? Which connections do you use it with, if not `rosbridge_suite` websocket server?

**Comment by gonzalocasas** [comment]
We definitely use it with `rosbridge_suite`, what we don't use it with is ros-sharp. That's why we detached it and made it a standalone project. If you'd split it on your official repo, we would drop our fork and use yours instead.

**Comment by MartinBischoff** [comment]
Ok, so you are fine with the [ros_sharp_communication launch file](https://github.com/siemens/ros-sharp/blob/master/ROS/file_server/launch/ros_sharp_communication.launch) launch file, but your issue is that the file_server is on the same repo as the rest of ROS#?

I agree that it is quite cumbersome to download a whole repo when you only need individual files. Please do feel free to split the ROS# code into individual repos as you need it for your application.

The advantages of keeping everything in one repo here are:
* We can always ensure consistency between ROS and .NET code; no discussion about which file_server version goes with that Unity3D version.
* Beginners immediately see what is needed on the ROS side to get things running and do not have to download code from different places.
