### ISSUE TITLE
Ros sharp close socket solutions

### ISSUE THREAD

**Issue by MinhDangTG** [siemens/ros-sharp#338]
---
## I have a question! ##
How can I solve the problem that Unity games sometimes crashed when I close the ros socket.

* My OS is: Windows 10 Pro
* My Unity Version is: Unity 2018.
* My ROS Distribution is: ROS Kinentic 16.04
* My Build Target Platform is: Windows

**Here is my bug description:**
I have been using the ROS# package for almost two years from the 11/2018. It has become a great contribution to my project by connecting the real robot with the simulated one in Unity. 

Recently, I tried to close all the ros sockets in the current scene (before going to another scene) to reduce the lag/delays of the simulated robot in the game after scenes. 

When I tried to close the socket using RosConnector.RosSocket.Close(), the lag/delays disappeared but the game sometimes crashed for some reasons.

The similar issue is #154. I figured out that updating ROS# package may remove this problem but we have been using this package (v1.3) for a long time. When I tried to replace it with a newer version (1.6), lots of errors came up and the configuration that we have been using, were lost. 

I had to fix the problem by putting the v1.3 package back. So how do I solve this problem without updating or updating the package but still keep our configuration (since we got lots of subscriber/publisher and a robot in every scene).

**Comment by MartinBischoff** [comment]
Hi @MinhDangTG ,
ROS# v1.3 is from Sep 2018, two years ago. I strongly suggest updating to a more recent version, even if it takes time to update your custom scripts. Here is the list of changes since version v1.3: https://github.com/siemens/ros-sharp/compare/v1.3...master#files_bucket

Some further hints:
* We already had [Protocols](https://github.com/siemens/ros-sharp/blob/v1.3/Libraries/RosBridgeClient/Protocols/IProtocol.cs) at that time. You can try and use your own Protocol implementation or update the respective Protocol only.
* Do the delays occur in both [WebSocketNetProtocol](https://github.com/siemens/ros-sharp/blob/master/Libraries/RosBridgeClient/Protocols/WebSocketNetProtocol.cs) and [WebSocketSharpProtocol](https://github.com/siemens/ros-sharp/blob/master/Libraries/RosBridgeClient/Protocols/WebSocketSharpProtocol.cs)?
* ROS# contains the sources of [WebSocketNetProtocol](https://github.com/siemens/ros-sharp/blob/master/Libraries/RosBridgeClient/Protocols/WebSocketNetProtocol.cs). Here is the `Close()` method: [WebSocketNetProtocol](https://github.com/siemens/ros-sharp/blob/master/Libraries/RosBridgeClient/Protocols/WebSocketNetProtocol.cs#L80). Please feel free to adjust it to your needs.
