### ISSUE TITLE
ROS Bridge connects but throws an error: unknown error handler name 'rosmsg'

### ISSUE THREAD

**Issue by yohannes-taye** [siemens/ros-sharp#348]
**Here is my problem:**
I have Ubuntu 14 setup on a VM and Unity 2019.4 on Windows. I have cloned the repo and started following the tutorials. Everything went well with setting up ROS, Turtle bot, and Gazebo. It worked till I reached the part of the tutorial 2.1 Transfer URDF from ROS to Unity. On the Unity side, this is what I get 
![image](https://user-images.githubusercontent.com/32170806/96248536-4a619e80-0fde-11eb-8320-3b233beba984.png)

While on the ros side it shows the following error 
![image](https://user-images.githubusercontent.com/32170806/96248603-5f3e3200-0fde-11eb-9fa7-f0252a84e784.png)

At this point, I'm stuck and don't know what else to try. I have looked at several of the issues on this repo, tried the proposed solutions but the issue still persists.

**Comment by berkayalpcakal** [comment]
Hello @yohannes-taye ,

I have searched this issue on web, it seems like this issue is related to your ROS environment on your Ubuntu. Here are some suggestions that I found;

* `sudo apt-get update && sudo apt-get upgrade` 
* `sudo apt install ros-$ROS_DISTRO-rosbridge-suite`
* `sudo apt install ros-$ROS_DISTRO-genpy `

I hope this helps.

**Comment by yohannes-taye** [comment]
Thank you so much @berkayalpcakal!! That fixed my issue :)
