### ISSUE TITLE
Joint read angle bug 

### ISSUE THREAD

**Issue by Tonirayn** [siemens/ros-sharp#365]
## I found a bug! ##
* [X] I am using the latest ROS# version available here on the master branch.
* [X] I am adding all required information, code and data files, screenshots and log files so that you can reproduce the problem.

* My OS is: Ubuntu 18.04
* My Unity Version is:  Unity 2020.2b
* My ROS Distribution is: Melodic
* My Build Target Platform is: linux86_64

**Here is my bug description:**
When the read function for the joints is called, you take the hinge angle of the joint but it is expressed in the global frame. 

Perform the following steps reproduce the bug:
I have a robotic arm and I move the first joint and I read the angle of the second one it appears changed, and that is wrong since I didn't rotate the second joint around its axis.

Observed results:
![Unity](https://user-images.githubusercontent.com/45395169/100878502-31d01980-34a2-11eb-9735-a1e78b532fb0.png)

Expected results:
![gazebo](https://user-images.githubusercontent.com/45395169/100878527-3b598180-34a2-11eb-8b61-77cb552dd9f4.png)

Relevant Code:
in UrdfJointRevolute.cs
```
  public override float GetPosition()
        {
            return -((HingeJoint)UnityJoint).angle * Mathf.Deg2Rad;
        }

```

**Comment by berkayalpcakal** [comment]
Hello @Tonirayn,

This issue has been discussed before in #330. At that time, we did not want to add a manual angle calculation routine to ROS# because wrong angle calculation ofHingeJoint has been a problem of Unity for a long time and should be fixed by Unity. 

We decided add a small get around with #367, hoping to remove it after Unity fixes angle calculation in HingeJoint.
