### ISSUE TITLE
How can I send data over Ubuntu to  Windows Hololense?

### ISSUE THREAD

**Issue by juliatum** [siemens/ros-sharp#382]
## I have a question! ##

* [ x] I searched the [Wiki](https://github.com/siemens/ros-sharp/wiki), [open](https://github.com/siemens/ros-sharp/issues) and [closed](https://github.com/siemens/ros-sharp/issues?q=is%3Aissue+is%3Aclosed) issues for an answer. I tried my best to find the answer by myself without success. I believe that the discussion we will have in this issue, and the solutions we might find, will help me, and likely other community members who have a similar problem.

**Here is my question:**
How can I send data over WIFI to Hololense2? My Ubuntu publishes Data. Unity Subscribes this Data. 
In the "play-Mode" everything is correct and it works. After succsessfull Deploy to Hololense2, i dont recive any data?
How can i slove this?

**Comment by berkayalpcakal** [comment]
Hello @juliatum,

Do you think that this issue is related to #201, #278?
Have you tried [this](https://github.com/EricVoll/ros-sharp) UWP version of ROS# fork?

I would suggest that you go over the closed issues regarding hololens, and try out the aforementioned fork. I will close this issue for the time being.
