### ISSUE TITLE
rotation frame

### ISSUE THREAD

**Issue by jocacace** [siemens/ros-sharp#390]
Hi guys,

I am not able to understand the rotation frame of an object. In particular, when I use the Pose subscriber I specify the object transform in the script parameter. However, it seems that the object rotates in the world frame and not in the body frame. Differently, using the twist script, velocity data are applied in the body frame. Can someone clarify this point?

Regards,

**Comment by MartinBischoff** [comment]
Hi @jocacace ,

all your statements above are correct. Clarification:

[Twist](http://docs.ros.org/en/melodic/api/geometry_msgs/html/msg/Twist.html) specifies linear and angular velocities of an object. [Pose](http://docs.ros.org/en/melodic/api/geometry_msgs/html/msg/Pose.html) specifies the position and orientation of an object.

In the scripts [TwistSubscriber](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/RosCommuncation/TwistSubscriber.cs) and [TwistPublisher](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/RosCommuncation/TwistPublisher.cs), twist is read / written in **local** frame.
In the scripts [PoseStampedSubscriber](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/RosCommuncation/PoseStampedSubscriber.cs) and  [PoseStampedPublisher](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/RosBridgeClient/RosCommuncation/PoseStampedPublisher.cs) pose is read / written in **global** frame.

We wrote those scripts this way a long time ago since we found this convention most reasonable and practical in our projects. I don't remember if I found a ROS reference specifying this convention or it just fit best to the robots we worked with.

Feel free to change these scripts - as well as all other ROS# scripts - to your liking!
Unity [Transform](https://docs.unity3d.com/ScriptReference/Transform.html) has many methods to quickly set or convert points, directions and vectors in/to local and gobal space and back.

If you find an official ROS statement that defines in which frame Twist and Pose should generally be specified, to which contradicts our convention above, please do share this info or send a pull request with the corrections.

Best regards!
