### ISSUE TITLE
Texture2D to CompressedImage ROS lagging on the client.

### ISSUE THREAD

**Issue by pushkalkatara** [siemens/ros-sharp#43]
* [x] I am at the right place and my issue is directly related to ROS#. General technical questions I would post e.g. at [ROS Answers](https://answers.ros.org/) or [Stackoverflow](https://stackoverflow.com). For library-specific questions I would look for help in the corresponding library forums.
* [x] I have throughly read [the Contributing Guideline](Contributing.md) and writing this issue is the right thing to do in my case.
---
## I found a bug! ##
* [x] I am using the latest ROS# version available here on the master branch.
* [x] I am adding all required information, code and data files, screenshots and log files so that you can reproduce the problem.

* My OS is: Ubuntu 16.04
* My Unity Version is: 
* My ROS Distribution is: ROS Kinectic
* My Build Target Platform is: 

**Here is my bug description:**

Texture2D is being published using these scripts:
https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/CameraImageManager.cs
https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/CameraImagePublisher.cs
But the FPS received on the Client from Unity is very low and the video is lagging.

Perform the following steps reproduce the bug:

Observed results:

![ezgif com-optimize](https://user-images.githubusercontent.com/21266230/36175433-6f8ce728-1135-11e8-8914-3eb035d62b76.gif)
Lag observed on the client side. Also the server is hosted on localhost and ethernet powered, so most probably not an issue of network.

Expected results:

No Lag.

Relevant Code:
```
<!-- Insert code here, optionally attrach code or data files to this issue. -->
```

**Comment by MartinBischoff** [comment]
This is a jitter you see here in RViz since your ROS System (rosbridge_suite and/or rviz) receives too many image publications, more than it can handle. It even mixes the order images are illustrated in Rviz since there are arriving so fast.

Looking at [CameraImageManager](https://github.com/siemens/ros-sharp/blob/master/Unity3D/Assets/RosSharp/Scripts/CameraImageManager.cs) we see that images are published every single frame in Unity.

Solutions: 
* Reduce the image message publication frequency in Unity
* (and/or give your ROS system more resources.)


You can reduce that e.g. by adding something like:
``` 
public int FrameSkip = 10;

[...]

private void Update()
{
   if (Time.frameCount % FrameStep == 0)
   {
    <trigger message publication here>
    }
}
[...]
```
then play with the `FrameSkip` number to optimzie the performance for your system.

In the new message handling framework (see issue #23 ) this parameter is available in the generic Unity publisher component.

**Comment by MartinBischoff** [comment]
@pushkalkatara does the suggested solution solve your problem? If so, please close the issue.

**Comment by pushkalkatara** [comment]
Yes. Thanks for the solution. Closing the issue.
