### ISSUE TITLE
Unity 2019.4 Importing issues: System.Memory&System.Threading.Tasks.Extensions

### ISSUE THREAD

**Issue by ShawnZhou997** [siemens/ros-sharp#471]
Hi, 
I created an empty Unity project with Unity 2019.4.40.f1c1 and imported ROS# via git URL, then I did nothing.
There are 2 types of errors showed:

`Library\PackageCache\com.siemens.ros-sharp@2d817a6025\Runtime\Libraries\RosBridgeClient\Serializers\MicrosoftSerializer.cs(53,20): error CS0012: The type 'ReadOnlySpan<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`
`Library\PackageCache\com.siemens.ros-sharp@2d817a6025\Runtime\Libraries\RosBridgeClient\Serializers\MicrosoftSerializer.cs(32,39): error CS0012: The type 'ReadOnlyMemory<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

System.Memory and System.Threading.Tasks.Extentions
It seems like I should assign them manually and so I did but end up in vian.
I've tried switch both the _.NET_  4.x and standard 2.0, too.
![image](https://github.com/user-attachments/assets/8cb03339-ebd8-424a-b300-b5ef36758503)

---
Is there anything I can do to solve this?

**Comment by memrecakal** [comment]
Hi @ShawnZhou997, this is a known issue with the older versions of Unity due to outdated included dlls within Unity. The minimum supported Unity version for ROS# 2.0.0 is 2022.3.17f1, see [platforms support](https://github.com/siemens/ros-sharp/tree/master?tab=readme-ov-file#platform-support) and [external dependencies](https://github.com/siemens/ros-sharp/wiki/Dev_ExternalDependencies). I don't recommend it, but for older Unity versions you may have to play with dlls manually, see [Unity configuration](https://github.com/siemens/ros-sharp/wiki/User_Inst_Unity3DOnWindows). I would recommend updating Unity or downgrading ROS#.
